#!/bin/bash
#
# NEXUS OS - Pre-start checks for Geth service
# Ensures blockchain is properly initialized before starting
#
set -e

LOG_FILE="/var/log/nexus-geth-prestart.log"
BLOCKCHAIN_DIR="/opt/nexus/blockchain"
DATA_DIR="${BLOCKCHAIN_DIR}/data"
KEYSTORE_DIR="${BLOCKCHAIN_DIR}/keystore"
WALLET_FILE="/opt/nexus/device_wallet.txt"
GENESIS_FILE="${BLOCKCHAIN_DIR}/genesis.json"
ENV_FILE="${BLOCKCHAIN_DIR}/environment"

log() {
    echo "[NEXUS Geth Pre-Start $(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "${LOG_FILE}"
}

error() {
    echo "[NEXUS ERROR $(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "${LOG_FILE}" >&2
    exit 1
}

warn() {
    echo "[NEXUS WARNING $(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "${LOG_FILE}"
}

log "Running pre-start checks..."

# Check if Geth is installed
if ! command -v geth &> /dev/null; then
    log "Geth not found, attempting to install..."

    # Try to add Ethereum PPA and install
    if command -v add-apt-repository &> /dev/null; then
        add-apt-repository -y ppa:ethereum/ethereum 2>/dev/null || true
        apt-get update
        apt-get install -y ethereum
    else
        error "Geth not installed and cannot be auto-installed"
    fi
fi

log "Geth version: $(geth version | head -n1)"

# Check for device wallet
if [ ! -f "${WALLET_FILE}" ]; then
    log "Device wallet not found, generating..."

    # Ensure keystore directory exists
    mkdir -p "${KEYSTORE_DIR}"
    chmod 700 "${KEYSTORE_DIR}"

    # Generate password
    DEVICE_ID=$(hostname)
    PASSWORD="nexus-${DEVICE_ID}-$(openssl rand -hex 16)"
    echo "${PASSWORD}" > "${BLOCKCHAIN_DIR}/password.txt"
    chmod 600 "${BLOCKCHAIN_DIR}/password.txt"

    # Create wallet
    WALLET_OUTPUT=$(geth account new \
        --keystore "${KEYSTORE_DIR}" \
        --password "${BLOCKCHAIN_DIR}/password.txt" 2>&1)

    # Extract address
    WALLET_ADDR=$(echo "${WALLET_OUTPUT}" | grep -oP '(?<=Public address of the key:   )[0-9a-fA-Fx]+' || \
                  geth account list --keystore "${KEYSTORE_DIR}" 2>/dev/null | grep -oP '(?<={)[^}]+' | head -1)

    if [ -z "${WALLET_ADDR}" ]; then
        error "Failed to generate device wallet"
    fi

    # Ensure 0x prefix
    if [[ ! "${WALLET_ADDR}" =~ ^0x ]]; then
        WALLET_ADDR="0x${WALLET_ADDR}"
    fi

    echo "${WALLET_ADDR}" > "${WALLET_FILE}"
    chmod 644 "${WALLET_FILE}"

    log "Device wallet generated: ${WALLET_ADDR}"
fi

WALLET_ADDR=$(cat "${WALLET_FILE}")
log "Device wallet: ${WALLET_ADDR}"

# Create/update environment file
cat > "${ENV_FILE}" << EOF
# NEXUS OS Blockchain Environment
# Auto-generated by pre-start script
NEXUS_WALLET_ADDRESS=${WALLET_ADDR}
EOF

# Check for genesis block
if [ ! -f "${GENESIS_FILE}" ]; then
    log "Genesis block not found, creating default..."

    # Extract address without 0x for extradata
    ADDR_NO_PREFIX="${WALLET_ADDR#0x}"

    # Create minimal genesis for single node
    cat > "${GENESIS_FILE}" << EOF
{
  "config": {
    "chainId": 123454321,
    "homesteadBlock": 0,
    "eip150Block": 0,
    "eip155Block": 0,
    "eip158Block": 0,
    "byzantiumBlock": 0,
    "constantinopleBlock": 0,
    "petersburgBlock": 0,
    "istanbulBlock": 0,
    "clique": {
      "period": 5,
      "epoch": 30000
    }
  },
  "difficulty": "1",
  "gasLimit": "8000000",
  "extradata": "0x0000000000000000000000000000000000000000000000000000000000000000${ADDR_NO_PREFIX}0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "alloc": {
    "${WALLET_ADDR}": { "balance": "1000000000000000000000" }
  }
}
EOF

    log "Genesis block created"
fi

# Initialize blockchain if needed
if [ ! -d "${DATA_DIR}/geth" ]; then
    log "Initializing blockchain database..."

    mkdir -p "${DATA_DIR}"

    geth init \
        --datadir "${DATA_DIR}" \
        "${GENESIS_FILE}"

    log "Blockchain database initialized"
else
    log "Blockchain database already initialized"
fi

# Check password file
if [ ! -f "${BLOCKCHAIN_DIR}/password.txt" ]; then
    error "Password file not found: ${BLOCKCHAIN_DIR}/password.txt"
fi

# Verify keystore has accounts
ACCOUNT_COUNT=$(geth account list --keystore "${KEYSTORE_DIR}" 2>/dev/null | wc -l)
if [ "${ACCOUNT_COUNT}" -eq 0 ]; then
    error "No accounts found in keystore"
fi

log "Found ${ACCOUNT_COUNT} account(s) in keystore"

# All checks passed
log "Pre-start checks completed successfully"
log "Ready to start Geth blockchain kernel"
