#!/bin/bash
#
# NEXUS OS - Run first-run.d scripts in order
# This script is executed once on first boot after setup
#
set -e

LOG_FILE="/var/log/nexus-first-run.log"
FIRSTRUN_DIR="/opt/nexus/first-run.d"

log() {
    echo "[NEXUS First-Run $(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "${LOG_FILE}"
}

error() {
    echo "[NEXUS ERROR $(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "${LOG_FILE}" >&2
}

# Create log directory if needed
mkdir -p "$(dirname ${LOG_FILE})"

log "========================================="
log "NEXUS OS First Boot Configuration"
log "========================================="

# Ensure state directory exists
mkdir -p /var/lib/nexus

# Check if first-run.d directory exists
if [ ! -d "${FIRSTRUN_DIR}" ]; then
    log "First-run directory not found: ${FIRSTRUN_DIR}"
    log "Looking for alternative locations..."

    # Try alternative locations
    for alt_dir in "/home/user/Nexus-OS/first-run.d" "/root/Nexus-OS/first-run.d"; do
        if [ -d "${alt_dir}" ]; then
            log "Found first-run.d at ${alt_dir}, copying..."
            mkdir -p "${FIRSTRUN_DIR}"
            cp -r "${alt_dir}/"* "${FIRSTRUN_DIR}/"
            chmod +x "${FIRSTRUN_DIR}/"*
            break
        fi
    done
fi

if [ ! -d "${FIRSTRUN_DIR}" ]; then
    error "No first-run.d directory found. Skipping first-run."
    exit 0
fi

# Count scripts
SCRIPT_COUNT=$(find "${FIRSTRUN_DIR}" -type f -executable 2>/dev/null | wc -l)
log "Found ${SCRIPT_COUNT} first-run scripts"

# Run scripts in sorted order (by filename)
COUNTER=0
for script in $(find "${FIRSTRUN_DIR}" -type f -executable 2>/dev/null | sort); do
    COUNTER=$((COUNTER + 1))
    SCRIPT_NAME=$(basename "${script}")

    log "[$COUNTER/$SCRIPT_COUNT] Running: ${SCRIPT_NAME}"

    if bash "${script}" >> "${LOG_FILE}" 2>&1; then
        log "[$COUNTER/$SCRIPT_COUNT] Completed: ${SCRIPT_NAME}"
    else
        EXIT_CODE=$?
        error "[$COUNTER/$SCRIPT_COUNT] Failed: ${SCRIPT_NAME} (exit code: ${EXIT_CODE})"
        # Continue with other scripts even if one fails
    fi
done

# Create environment file for Geth service
if [ -f "/opt/nexus/device_wallet.txt" ]; then
    WALLET_ADDR=$(cat /opt/nexus/device_wallet.txt)
    cat > /opt/nexus/blockchain/environment << EOF
# NEXUS OS Blockchain Environment
# Auto-generated by first-run script
NEXUS_WALLET_ADDRESS=${WALLET_ADDR}
EOF
    log "Created blockchain environment file"
fi

log "========================================="
log "NEXUS OS First Boot Configuration Complete"
log "========================================="

# Final status
log "System ready for blockchain operations"
log "Wallet: $(cat /opt/nexus/device_wallet.txt 2>/dev/null || echo 'Not configured')"
log "Node ID: $(cat /opt/nexus/node_id 2>/dev/null || echo 'Not assigned')"
